version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: logitrack
      POSTGRES_USER: logitrack
      POSTGRES_PASSWORD: logitrack
    restart: always
    volumes:
      - '/var/lib/postgresql/data/pgdata'
  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 2345:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    restart: always
  vernemq:
    build: .
    ports:
      - 1883:1883
      - 8883:8883
    depends_on:
      - postgres
    restart: always
