version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: logitrack
      POSTGRES_USER: logitrack
      POSTGRES_PASSWORD: logitrack
    restart: always
  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 2345:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    restart: always
  # vernemq:
  #   image: erlio/docker-vernemq:latest-alpine
  #   ports:
  #     - 1883:1883
  #     - 1880:8080
  #   environment:
  #     DOCKER_VERNEMQ_USER_test: test
